### ISSUE TITLE
Add persistent volume

### ISSUE THREAD

**Issue by Jcambass** [directus/directus-docker#11]
The directus docker image should contain a Volume where all uploaded files etc. should be persisted. The same goes for the MySQL Database

**Comment by WellingGuzman** [comment]
Thanks for the suggestion, if someone want to jump in to support this, I'd be glad, otherwise it will need to wait until the release of Directus 6.4

**Comment by wittwerch** [comment]
@Jcambass Whether to persist data or not is up to your configuration. You can use a second configuration file to override some values from the docker-compose.yml.

docker-compose.override.yml
```
version: '2'
services:
  directus:
    volumes:
      - "/volumes/directus-app:/var/www/html/storage"
  mysql:
    volumes:
      - "/volumes/directus-mysql:/var/lib/mysql"
```

The host mount will make sure, that Directus and MySQL data is persisted even when your containers get recreated/destroyed.
Disclaimer: Did not test the entire configuration, but adapted it from another use case. But I think it should do the trick.
