### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by soapoperator** [directus/directus-docker#25]
I clone the project and run the container after some modifications in the docker-compose file like this:
```
version: '2'
#
# [ server stack ]
#
services:
  mysql:
    image: mariadb:latest
    container_name: directus-mrdb
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=directus
     - MYSQL_DATABASE=directus
     - MYSQL_USER=directus
     - MYSQL_PASSWORD=directus
    # If you need to specify a persistent volume for mysql
    volumes:
      - ./data/db:/var/lib/mysql
  directus:
    depends_on:
       - mysql
    image: getdirectus/directus:6.4
    container_name: directus
    # links:
    #  - mysql:mysql
    ports:
     - 8585:8080
    restart: always
    volumes:
    # Switch between named storage, path storage
     - ./data/storage:/var/www/html/storage 
    environment:
     - MYSQL_USER=directus
     - MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_DATABASE=directus
     - MYSQL_PORT_3306_TCP_ADDR=mysql
     - MYSQL_PORT_3306_TCP_PORT=3306
```

After ligin into Directus, i try to make some configuration.
Then i get a permission error when i try to add files:
```
Server Error
Impossible to create the root directory "/var/www/html/storage/uploads".
```
I guest it's a issue with the user used in the dockerfile. So i remove the www-data mention without success.

Any help will be appreciate?
